[build]
  command   = "npm install && npx expo export --platform web"
  publish   = "dist"

[build.environment]
  NODE_VERSION = "20.17.0"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Redireciona todas as rotas para index.html (SPA)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
